# params.yaml
random_state: 42

split:
  test_size: 0.2
  stratify_col: VENTAJA
  cv_n_splits: 5

selection:
  metric: roc_auc

train:
  rf:
    n_estimators: 300
  xgb:
    n_estimators: 300
    objective: "binary:logistic"
    eval_metric: "logloss"

tune:
  n_iter: 50
  scoring: roc_auc
  xgb_param_distributions:
    n_estimators: [1500, 2000, 2500]
    max_depth: [8, 10]
    learning_rate: [0.07, 0.08, 0.1]
    subsample: [0.8]
    colsample_bytree: [0.5, 0.6, 0.7]
    min_child_weight: [3]
    reg_alpha: [0, 0.02, 0.05]
    reg_lambda: [1.5, 2.5, 3, 3.5]
  rf_param_distributions:
    n_estimators: [1500, 2000, 2500]
    max_depth: [null]
    min_samples_split: [2]
    min_samples_leaf: [1]
    max_features: ["sqrt", "log2", 0.4, 0.5]

mlflow:
  experiment_name: ml_dice_game
  registered_model_name: ml_dice_game_ventaja_classifier